apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: o6j2fsw7p-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/o6j2fsw7p-java-quarkus-gitops